meta:
  image: pojntfx/ipxebuilderd:latest
  dev: false
  debugPort: 31441
  debugNodePort: 31441
  target: "{{ .TARGET }}"
  platform: "{{ .TARGETPLATFORM }}"
  debug: "{{ .DEBUG }}"

resources:
  memory: "128Mi"
  cpu: "512m"
  maxReplicas: 10

ingress:
  nodePort: 31440
  domain: ipxebuilderd.felix.pojtinger.com
  path: /

S3:
  bucket: ipxebuilderd

minio:
  ingress:
    enabled: true
    hosts:
      - name: minio.ipxebuilderd.felix.pojtinger.com
  accessKey:
    password: ipxebuilderUser
  secretKey:
    password: ipxebuilderPassword
