meta:
  image: pojntfx/ipxebuilderd:latest
  dev: false

resources:
  memory: "128Mi"
  cpu: "512m"
  maxReplicas: 10

ingress:
  nodePort: 31440
  domain: ipxebuilderd.felix.pojtinger.com
  path: /

S3:
  bucket: ipxebuilderd

minio:
  ingress:
    enabled: true
    hosts:
      - name: minio.ipxebuilderd.felix.pojtinger.com
  accessKey:
    password: ipxebuilderUser
  secretKey:
    password: ipxebuilderUser
